name: Generate GitHub Contribution Snake

on:
  # Executa a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  # Permite executar manualmente pela aba Actions do GitHub
  workflow_dispatch:
  # Opcional: Executa também quando um push é feito para a branch main (se você atualizar o README, por exemplo)
  push:
    branches:
      - main # ou master, dependendo da sua branch principal

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      # Necessário para que a action possa fazer commit da imagem gerada no seu repositório
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # Seu nome de usuário do GitHub
          github_user_name: ${{ github.repository_owner }} # Pega automaticamente o dono do repo (IsaqueCodeX)

          # Lista de arquivos de saída para a animação da cobrinha
          # dist/github-snake.svg será o arquivo padrão gerado
          # dist/github-snake-dark.svg para o tema escuro com ?palette=github-dark
          # dist/ocean.gif para um tema oceano em formato GIF
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist
          # Verifica se há mudanças para commitar
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Generate contribution snake animation"
            git push
          fi
